services:
  - postgresql

before_install:
  - echo '--colour' > ~/.rspec
  - 'echo ''gem: --no-document'' > ~/.gemrc'

before_script:
  - psql -c 'CREATE DATABASE translation_server_test;' -U postgres
  - bin/setup

cache:
  - bundler

language:
  - ruby

notifications:
  email:
    - false
rvm:
  - 2.6.1

script:
  - bundle exec rspec

env:
  - RAILS_ENV=test
